# Site settings
title: Thunder Hawk Security Solutions
email: thunderhawksec@thunderhawk.com.br
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/portal/" # the subpath of your site, e.g. /blog/
url: "http://thunderhawk.github.io/" # the base hostname & protocol for your site

# User setting
owner: CD2E2J
email: thunderhawksec@thunderhawk.com.br
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key: AIzaSyAryNQXEqfFknQ7dj3Qyz2KTowWNzqP2oU

# Build settings
markdown: kramdown